### PR TITLE
Add Rewrapped instances.

### PR DESCRIPTION
**Pull request by quasicomputational**
CI is going to fail because of #37, probably, but I verified it builds locally.

### CODE REVIEW

**Comment by quasicomputational** [comment]
Rebased on master, so let's see if it passes CI...

**Comment by quasicomputational** [comment]
Rebased. Ping?

**Comment by quasicomputational** [comment]
@ali-abrar, is there anything I need to do to unblock this?

**Comment by ali-abrar** [comment]
Apologies for the delay.

**Pull request merged**
