### PR TITLE
Few additions to the lib

### PR DESCRIPTION
**Pull request by k-bx**
Hi!

I finally managed to migrate my home-grown monoid hm type to your library, thanks for your work!

Here are few additions. I hope they're good. If not -- I'm ready to change PR based on your feedback :)

Thanks!

### CODE REVIEW

**Comment by k-bx** [comment]
@bgamari sorry for annoyance, just wanted to ping you in case you've missed this one. Thanks!

**Comment by k-bx** [comment]
@bgamari ping :wave: :)

**Comment by bgamari** [comment]
Oh dear, I'm very sorry about the lack of response; somehow the messages for this repo have been getting sent to my spam folder.

Thanks for this

**Comment by k-bx** [comment]
Haha :) I was hoping that this is the reason. Thanks for merging!

**Comment by bgamari** [comment]
Released as 0.1.1.0

**Comment by bgamari** [comment]
Thanks for catching the `fromList` bug by the way; I feel quite silly for overlooking that.

**Comment by k-bx** [comment]
@bgamari yeah, it's good that my project's tests (since I had this when using HashMap) found it

**Pull request merged**
