### PR TITLE
Update for GHC 9.2

### PR DESCRIPTION
**Pull request by LightAndLight**

### CODE REVIEW

**Comment by mpickering** [comment]
@bgamari @ali-abrar ping, can you please also revise the bound on hackage?

**Comment by mpickering** [comment]
I revised the bounds on hackage so the package builds with 9.2.

**Comment by ocharles** [comment]
@bgamari @ali-abrar if you need help maintaining this package, I'm more than happy to help out with routine work (merging bump PRs, cutting minor releases, etc).

**Comment by ocharles** [comment]
It looks like this has already happened in `master`.

**Pull request closed without merging**
