### PR TITLE
Added Data.Map.Monoidal.Strict version

### PR DESCRIPTION
**Pull request by louispan**

### CODE REVIEW

**Comment by louispan** [comment]
Looks like Data.Map.Strict is not supported for GHC 7.4.2
Do you know how to #if out a module for a specific ghc version?

**Comment by bgamari** [comment]
This looks pretty reasonable to me, but let's try to avoid the conditional exports. Perhaps let's just take a `containers >= 0.5` constraint

**Comment by louispan** [comment]
The reason I had conditional bounds was to continue support for GHC 7.4.2.

If you are happy with removing support for GHC 7.4.2 then I will be able remove the conditional exports in the cabal file.

**Comment by bgamari** [comment]
louispan <notifications@github.com> writes:

> The reason I had conditional bounds was to continue support for GHC 7.4.2.
>
Perhaps I'm just being silly, but I don't see why one couldn't compile
`containers-0.5` with GHC 7.4 (unless, of course, you also need to link
against the `ghc` library, in which case you'd be forced to use
whichever GHC version was used by `ghc`).

**Comment by louispan** [comment]
Sorry that my comment wasn't clearer. I really meant to say there is containers-0.5 is not available for base 4.5.1.0

GCH 7.4.2 uses base 4.5.1.0 (https://wiki.haskell.org/Base_package)
which meant template-haskell must be 2.7.0.0
(https://hackage.haskell.org/package/template-haskell-2.7.0.0)
because template-haskell has the constraint
base (==4.5.*), but then 2.7.0.0 also have the constraint containers (==0.4.*), which conflicts with our containers >=0.5 requirement.

See https://travis-ci.org/bgamari/monoidal-containers/jobs/148218528

**Comment by bgamari** [comment]
Ahhh, I see. Tricky business. To be honest, given how much pain 7.4 is causing I'm rather leaning towards just dropping support for it if this is okay with you.

**Comment by louispan** [comment]
Okay, I'll modify the pull request to drop support for 7.4 and bump the monoidal-containers version to 0.3.0.0.

**Comment by louispan** [comment]
I decided to roll #12 into this pull request. Let me know if you don't like the constructor and selector names, and I'll change them.

**Comment by bgamari** [comment]
Thanks! Merged in 10b12b7f8b48b8f01a4959db7814c1dcedc702e1.

**Pull request closed without merging**
